"""Convert the official 3DBenchy.stl into src/benchy_mesh.scad (encoded points + faces).

usage: python -P build_data.py <3DBenchy.stl> <out benchy_mesh.scad>

- Drops the 299 stray sliver components (616 faces, ~0 volume); keeps the one real body.
- Coordinates rounded to 0.001 mm; faces emitted clockwise-from-outside (OpenSCAD order).
- Encoding: one UTF-8 character per integer (code point = 0x10000 + value), in short strings.
  A 7 MB nested-list literal takes ~100 s to parse in OpenSCAD 2021.01, and indexing one huge
  string is O(n) per lookup; short strings parse instantly and decode ~1M values in ~6 s.
"""
import sys
import numpy as np
import trimesh

src, dst = sys.argv[1], sys.argv[2]
m = trimesh.load(src, process=True)
parts = sorted(m.split(only_watertight=False), key=lambda p: -len(p.faces))
body = parts[0]
print("kept body faces", len(body.faces), "dropped", sum(len(p.faces) for p in parts[1:]))

v = np.round(body.vertices, 3) + 0.0          # +0.0 turns -0.0 into 0.0
uniq, inv = np.unique(v, axis=0, return_inverse=True)   # re-merge after rounding
f = inv.reshape(-1)[body.faces]
keep = (f[:, 0] != f[:, 1]) & (f[:, 1] != f[:, 2]) & (f[:, 0] != f[:, 2])
print("degenerate faces after rounding:", int((~keep).sum()))
f = f[keep][:, ::-1]                           # STL is CCW from outside; OpenSCAD wants CW

OFF = uniq.min(0)
q = np.rint((uniq - OFF) * 1000).astype(np.int64)
assert q.max() < 0xFFFFF and f.max() < 0xFFFFF
CH = 66 * 3                                    # integers per string chunk


def enc(flat):
    flat = flat.reshape(-1)
    chunks = ['"' + "".join(chr(0x10000 + int(x)) for x in flat[i:i + CH]) + '"'
              for i in range(0, len(flat), CH)]
    return ",\n".join(chunks)


with open(dst, "w", newline="\n", encoding="utf-8") as o:
    o.write("// GENERATED by tools/build_data.py from the official 3DBenchy.stl (CreativeTools, public domain).\n")
    o.write("// Do not edit by hand. %d points, %d faces, units mm, bow toward +X.\n" % (len(uniq), len(f)))
    o.write("// Each integer is one character (code point 0x10000+value); points are 0.001 mm steps from benchy_off.\n")
    o.write("benchy_off = [%s, %s, %s];\n" % tuple(repr(round(float(x), 3)) for x in OFF))
    o.write("benchy_pt_chunks = [\n" + enc(q) + "\n];\n")
    o.write("benchy_face_chunks = [\n" + enc(f) + "\n];\n")
    o.write("function benchy_points() = [for (s = benchy_pt_chunks) for (k = [0 : len(s) / 3 - 1])\n"
            "    [(ord(s[3*k]) - 65536) / 1000 + benchy_off[0],\n"
            "     (ord(s[3*k+1]) - 65536) / 1000 + benchy_off[1],\n"
            "     (ord(s[3*k+2]) - 65536) / 1000 + benchy_off[2]]];\n")
    o.write("function benchy_faces() = [for (s = benchy_face_chunks) for (k = [0 : len(s) / 3 - 1])\n"
            "    [ord(s[3*k]) - 65536, ord(s[3*k+1]) - 65536, ord(s[3*k+2]) - 65536]];\n")
print("points", len(uniq), "faces", len(f), "bounds", uniq.min(0), uniq.max(0))
